### ISSUE TITLE
Move API version from URL to accepts header?

### ISSUE THREAD

**Issue by buske** [MatchMakerExchange/mme-apis#30]
There is immense debate on this topic, but it seems to have become frowned upon to specify the API version in REST URLs.

**Comment by allasm** [comment]
The current pull request suggests it is possible to have no API version specified by the client and/or the server: "...If no version is specified, the remote server should respond in the latest version supported by the remote server...".

I think that may cause some troubles in the future, since once no explicit version checking is done thing will work fine until some version update will change something and wrong matches will be popping up or matches will be lost - but it will not be obvious what is going on since the queries & responses may be syntactically correct, just not interpreted the same way on the client and the server, or one of the sides may be ignoring some bits of information. Also, not checking versions is the easiest thing to do so if API does not require that we can expect some parties (e.g. some other projects who join MME) to skip the visioning part.

**Comment by fschiettecatte** [comment]
Maybe the easiest way to go would be to require a version (which is specified in the Content-type header anyway). I coded GeneMatcher to simply reject requests that don't contain it.

**Comment by allasm** [comment]
I agree. And the easiest way to implement different versions is to always reject non-matching versions, which should probably be fine most of the time - and only if someone really wants to a special check for compatible versions can be implemented or a server may provide different handlers for different protocol versions.

**Comment by buske** [comment]
+1 to requiring version in all cases.

**Comment by Relequestual** [comment]
Fixed with https://github.com/MatchMakerExchange/mme-apis/pull/63
