### ISSUE TITLE
Make "observed" field optional?

### ISSUE THREAD

**Issue by buske** [MatchMakerExchange/mme-apis#48]
This field seems to be very implementation specific, and not necessary for the core API we're trying to build right now (and I doubt many matchmakers will use non-`yes` terms for a while). We could nail down a proper explanation, but I think it makes sense to just get rid of it until we need it.

**Comment by allasm** [comment]
I think that it can be made optional (with the default value of "yes") but that it should be kept around, since potentially knowing that a phenotype is not present may improve matching algorithm's performance in the future.

If we keep it various providers are more likely to implement it and later silently benefit once any of the other matchers incorporates this info into their matching algorithm (since the info will already be sent around, just unused).  I saw GeneMatcher had both "observed:yes" and "observed:no" in its queries, and so does PhenomeCentral; so the information is clearly available and I don't think simplification which removes already available and easy-to implement information is a good idea. At the same time being optional it does not significantly increase cost of basic implementation and one field does not inflate the API a lot.

**Comment by buske** [comment]
Fair points.

**Comment by allasm** [comment]
But do we make it optional? And what do others say?

**Comment by buske** [comment]
Ah, yes,

**Comment by fschiettecatte** [comment]
I would make it optional. In PhenoDB we draw a distinction between 'yes', 'no' and 'unknown'. 'No' is for cases where you expect to see the features but did not see it, and 'unknown' is for cases where it is unknown whether the feature is present or not. For the purposes of matching, optional with a default of 'yes' is perfectly fine.

**Comment by Relequestual** [comment]
Resolved by https://github.com/MatchMakerExchange/mme-apis/pull/72
